# must be unique in a given SonarQube instance
sonar.projectKey=4s92bB3Xk

# this is the name displayed in the SonarQube UI
sonar.projectName=aloware-talk2
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

sonar.sources=./src/,./src-electron
