export const DEFAULT_STATE = {
  filter: {
    from_date: null,
    to_date: null,
    type: 'all',
    direction: 'all',
    report_type: 'date_v_campaign',
    chart_period: 'day',
    answer_status: 'all',
    export_type: 'json',
    min_talk_time: '0',
    contact_id: null,
    campaign_id: null,
    ring_group_id: null,
    user_id: null,
    workflow_id: null,
    page: 1,
    per_page: 20,
    checked_table_fields: null,
    first_time_only: 0,
    exclude_automated_communications: 0,
    untagged_only: 0,
    is_blocked: 0,
    is_dnc: 0,
    has_unread: 0,
    text_authorized: 0,
    lrn_types: [],
    tags: [],
    campaigns: [],
    workflows: [],
    ring_groups: [],
    incoming_numbers: [],
    users: [],
    timezone: window.timezone,
    changed: 0,
    transfer_type: null,
    call_dispositions: [],
    callback_status: null,
    broadcasts: [],
    mentioner_user_id: [],
    mentioned_user_id: [],
    last_engagement_date: {
      start: null,
      end: null
    },
    owner_id: null
  }
}
