// KYC form not submitted, aka “clicking around“
export const STATUS_KYC_0 = -1

// Trial is canceled, login will not work
export const STATUS_REJECTED_FRAUD = 0

// Rejected and needs resubmit
export const STATUS_REJECTED_RESUBMIT = 1

// Approved for self calling
export const STATUS_VERIFIED_RESTRICTED = 2

// All calling features are allowed
export const STATUS_VERIFIED_CALLING = 3

// All calling and texting are allowed
export const STATUS_VERIFIED_FULL = 4

export const ONESELF_CALLS_ALLOWED = [
  STATUS_KYC_0,
  STATUS_REJECTED_FRAUD,
  STATUS_VERIFIED_RESTRICTED,
  STATUS_VERIFIED_CALLING,
  STATUS_VERIFIED_FULL
]

export const CALLS_TO_OTHERS_ALLOWED = [
  STATUS_VERIFIED_CALLING,
  STATUS_VERIFIED_FULL
]

export const ONESELF_TEXTS_ALLOWED = [
  STATUS_KYC_0,
  STATUS_REJECTED_FRAUD,
  STATUS_VERIFIED_RESTRICTED,
  STATUS_VERIFIED_CALLING,
  STATUS_VERIFIED_FULL
]

export const TEXTS_TO_OTHERS_ALLOWED = [
  STATUS_VERIFIED_FULL
]

export const SINGLE_TEST_NUMBER_PURCHASED_ALLOWED = [
  STATUS_KYC_0,
  STATUS_REJECTED_FRAUD,
  STATUS_VERIFIED_RESTRICTED,
  STATUS_VERIFIED_CALLING,
  STATUS_VERIFIED_FULL
]

export const BUY_NEW_NUMBERS_ALLOWED = [
  STATUS_VERIFIED_FULL
]

export const IMPORT_CONTACTS_ALLOWED = [
  STATUS_VERIFIED_FULL
]

export const CREATE_CONTACTS_ALLOWED = [
  STATUS_VERIFIED_CALLING,
  STATUS_VERIFIED_FULL
]

export const VISIT_INTEGRATIONS_ALLOWED = [
  STATUS_KYC_0,
  STATUS_REJECTED_FRAUD,
  STATUS_VERIFIED_RESTRICTED,
  STATUS_VERIFIED_CALLING,
  STATUS_VERIFIED_FULL
]

export const PURCHASING_NUMBERS_ALLOWED = [
  STATUS_VERIFIED_FULL
]

export const SKIP_TRIAL_ALLOWED = [
  STATUS_VERIFIED_RESTRICTED,
  STATUS_VERIFIED_CALLING,
  STATUS_VERIFIED_FULL
]

export const VIEW_ONLY_ALLOWED = [
  STATUS_KYC_0,
  STATUS_REJECTED_RESUBMIT
]
