export const KYC_STATUS_NONE = 0
export const KYC_STATUS_ZERO = 1
export const KYC_STATUS_DEFINITELY_REJECTED = 2
export const KYC_STATUS_APPROVED_FOR_SELF_CALLING = 3
export const KYC_STATUS_APPROVED_FOR_CALLING_ONLY = 4
export const KYC_STATUS_APPROVED_FOR_CALLING_AND_MESSAGING = 5
