<template>
  <div>
    <vue-multiselect track-by="id"
                     label="name"
                     class="mr-1"
                     style="width: 100%"
                     placeholder="Select a sequence"
                     :searchable="true"
                     :showNoResults="false"
                     :close-on-select="true"
                     :options="formattedSequences"
                     :show-labels="false"
                     :allow-empty="false"
                     group-label="group"
                     group-values="sequences"
                     :group-select="false"
                     v-model="sequence">
    </vue-multiselect>
  </div>
</template>

<script>
import VueMultiselect from 'vue-multiselect'
import auth from 'boot/auth'
import { mapState } from 'vuex'
export default {
  name: 'sequence-selector',
  components: { VueMultiselect },
  props: {
    exclude: {
      required: false
    },
    blockBroadcast: {
      type: Boolean,
      required: false,
      default: false
    }
  },
  computed: {
    ...mapState({
      currentCompany: state => state.currentCompany
      // workflows: state => state.workflows
    }),
    formattedSequences () {
      let data = [
        {
          group: 'Active',
          sequences: this.availableWorkflows.filter(workflow => workflow.active)
        }
      ]

      data.push({
        group: 'Paused',
        sequences: this.availableWorkflows.filter(workflow => !workflow.active)
      })

      return data
    },
    availableWorkflows () {
      if (this.workflows) {
        return this.workflows.filter((workflow) => {
          if (this.blockBroadcast) {
            return workflow.id !== this.exclude
          }
          return workflow.id !== this.exclude
        }).sort((a, b) => {
          let textA = a.name.toUpperCase()
          let textB = b.name.toUpperCase()
          return (textA < textB) ? -1 : (textA > textB) ? 1 : 0
        })
      }

      return []
    }

  },
  data () {
    return {
      auth: auth,
      isLoading: false,
      sequence: null,
      workflows: [{
        'contacts_count': 0,
        'sequences_count': 8,
        'remaining_tasks': '0',
        'total_tasks': 0,
        'id': 242,
        'company_id': 7,
        'campaign_id': 10,
        'tag_id': null,
        'name': 'RemainingTasks',
        'description': null,
        'send_on': 1,
        'open': null,
        'close': null,
        'always_open': true,
        'do_not_enroll_after_hours': false,
        'triggers': null,
        'mailgun_intake_route': null,
        'disenroll_on_response': true,
        'disenroll_on_calls': false,
        'batch_size': 0,
        'active': true,
        'current_status': 1,
        'task_count': 0,
        'is_v2': 0,
        'process_on_holidays': false,
        'created_at': '2021-07-08 02:00:50',
        'process_condition': 'Process everyday<br/> at any time of the day.',
        'converted_open': null,
        'converted_close': null,
        'is_enrollable': true,
        'diagnosis': [{
          'name': 'Company is active',
          'value': true
        }, {
          'name': 'Line is active',
          'value': true
        }, {
          'name': 'Sufficient funds',
          'value': true
        }, {
          'name': 'Has steps',
          'value': true
        }],
        'real_status': 2,
        'campaign': {
          'id': 10,
          'company_id': 7,
          'ring_group_id': 32,
          'ivr_text_ring_group_id': null,
          'user_id': null,
          'default_filter_id': null,
          'name': 'Vulcan Hotel',
          'description': null,
          'should_greet': true,
          'greeting_tts': 'Welcome to Aloware',
          'greeting_file': null,
          'should_ask_for_text_authorization': false,
          'ask_for_text_authorization_tts': 'Press 1 for text message authorization.',
          'ask_for_text_authorization_file': null,
          'should_whisper': true,
          'whisper_tts': 'Hey [AgentName] This is a call from [CampaignName]!',
          'whisper_file': null,
          'should_record': true,
          'record_tts': 'Your call is being recorded for quality assurance purposes.',
          'record_file': null,
          'voicemail_tts': 'We are sorry, but no agents are available to take this call. Please leave your message after the beep.',
          'voicemail_file': null,
          'review_required': 1,
          'review_duration': 60,
          'is_proxy': 0,
          'caller_id_option': 1,
          'missed_call_handling_mode': 2,
          'missed_call_handling_options': '{"forward_to": "+18189005934", "reroute_to_campaign_id": null}',
          'call_router_behavior': 1,
          'ivr_prompt_tts': 'If you know your extension you can enter it now, if not Press 1 to connect to GoSite.',
          'ivr_prompt_file': null,
          'should_message_if_missed': false,
          'missed_call_message': null,
          'should_block_spam': false,
          'created_at': '2018-02-02 04:37:23',
          'updated_at': '2021-07-08 14:45:01',
          'type': 0,
          'subtype': null,
          'is_fax': false,
          'operating_hours': '{"friday": [{"id": "5", "open": "24hrs", "close": "24hrs", "isOpen": true}], "monday": [{"id": "1", "open": "24hrs", "close": "24hrs", "isOpen": true}], "sunday": [{"id": "7", "open": "24hrs", "close": "24hrs", "isOpen": true}], "tuesday": [{"id": "2", "open": "24hrs", "close": "24hrs", "isOpen": true}], "saturday": [{"id": "6", "open": "24hrs", "close": "24hrs", "isOpen": true}], "thursday": [{"id": "4", "open": "24hrs", "close": "24hrs", "isOpen": true}], "wednesday": [{"id": "3", "open": "24hrs", "close": "24hrs", "isOpen": true}]}',
          'closed_hours_voice_prompt': '{"tts": null, "file": null, "enabled": false}',
          'closed_hours_auto_reply_text': '{"enabled": false, "message": null}',
          'triggers': '[{"id": "52102498-c925-4e93-98d3-d9f56614bfff", "type": "contact", "valid": true, "value": 0, "symbol": null, "tag_ids": [27], "keywords": [], "variable": null, "direction": null, "operation": "tag", "workflow_ids": [], "has_condition": false, "disposition_status": null, "disposition_status_id": []}]',
          'ivr_steps': '[{"id": "2e7f79f3-23f0-4919-b423-b5740e717516", "key": null, "task": "route_to_extension", "type": "normal", "valid": true, "tag_ids": [], "message_tts": null, "message_file": null, "workflow_ids": [], "route_to_user_id": null, "call_router_behavior": 1, "listen_for_extension": true, "reroute_to_campaign_id": null, "route_to_ring_group_id": false, "route_to_destination_id": false}, {"id": "16a2ad16-902c-4b36-97dc-9b38b673bd32", "key": "*", "task": "replay", "type": "normal", "valid": true, "tag_ids": [], "message_tts": null, "message_file": null, "workflow_ids": [], "route_to_user_id": null, "call_router_behavior": null, "listen_for_extension": false, "reroute_to_campaign_id": null, "route_to_ring_group_id": null, "route_to_destination_id": null}, {"id": "e03c5f16-fdb0-4dfd-a1b2-67f09c7ed4fe", "key": null, "task": "replay", "type": "exit", "valid": true, "tag_ids": [], "message_tts": null, "message_file": null, "workflow_ids": [], "route_to_user_id": null, "call_router_behavior": null, "listen_for_extension": false, "reroute_to_campaign_id": null, "route_to_ring_group_id": null}, {"id": "d2828df6-eb04-47d0-bad1-49643c15b82b", "key": "1", "task": "route_to_ring_group", "type": "normal", "valid": true, "tag_ids": [], "message_tts": null, "message_file": null, "workflow_ids": [], "route_to_user_id": null, "call_router_behavior": null, "listen_for_extension": false, "reroute_to_campaign_id": null, "route_to_ring_group_id": 188, "route_to_destination_id": null}]',
          'pool_size': null,
          'pool_options': null,
          'visitor_tracking_mode': null,
          'visitor_tracking_options': null,
          'active': true,
          'tracking_source': null,
          'has_messaging_service': false,
          'dni_script_address': 'https://app.alodev.org/v1/sZwMTAmV/dni.js',
          'incoming_number': '+18583608237',
          'first_incoming_number': {
            'id': 2034,
            'company_id': 7,
            'campaign_id': 10,
            'phone_number': '+18583608237',
            'city': '',
            'state': 'CA',
            'country': 'US',
            'label': 'Vulcan Hotels-incoming number',
            'non_billable': false,
            'is_tollfree': false,
            'is_rented': true,
            'do_not_use': false,
            'is_voice_capable': true,
            'is_fax_capable': true,
            'is_sms_capable': true,
            'is_mms_capable': true,
            'is_fax': false,
            'default_callerid': false,
            'created_at': '2021-05-27 21:33:10',
            'updated_at': '2021-07-08 06:00:09'
          }
        }
      },
      {
        'contacts_count': 2,
        'sequences_count': 2,
        'remaining_tasks': '4',
        'total_tasks': 4,
        'id': 241,
        'company_id': 7,
        'campaign_id': 10,
        'tag_id': null,
        'name': 'AddtoContact',
        'description': null,
        'send_on': 1,
        'open': null,
        'close': null,
        'always_open': true,
        'do_not_enroll_after_hours': false,
        'triggers': null,
        'mailgun_intake_route': null,
        'disenroll_on_response': true,
        'disenroll_on_calls': false,
        'batch_size': 0,
        'active': false,
        'current_status': 1,
        'task_count': 0,
        'is_v2': 0,
        'process_on_holidays': false,
        'created_at': '2021-07-03 04:50:22',
        'process_condition': 'Process everyday<br/> at any time of the day.',
        'converted_open': null,
        'converted_close': null,
        'is_enrollable': true,
        'diagnosis': [{
          'name': 'Company is active',
          'value': true
        }, {
          'name': 'Line is active',
          'value': true
        }, {
          'name': 'Sufficient funds',
          'value': true
        }, {
          'name': 'Has steps',
          'value': true
        }],
        'real_status': 2,
        'campaign': {
          'id': 10,
          'company_id': 7,
          'ring_group_id': 32,
          'ivr_text_ring_group_id': null,
          'user_id': null,
          'default_filter_id': null,
          'name': 'Vulcan Hotel',
          'description': null,
          'should_greet': true,
          'greeting_tts': 'Welcome to Aloware',
          'greeting_file': null,
          'should_ask_for_text_authorization': false,
          'ask_for_text_authorization_tts': 'Press 1 for text message authorization.',
          'ask_for_text_authorization_file': null,
          'should_whisper': true,
          'whisper_tts': 'Hey [AgentName] This is a call from [CampaignName]!',
          'whisper_file': null,
          'should_record': true,
          'record_tts': 'Your call is being recorded for quality assurance purposes.',
          'record_file': null,
          'voicemail_tts': 'We are sorry, but no agents are available to take this call. Please leave your message after the beep.',
          'voicemail_file': null,
          'review_required': 1,
          'review_duration': 60,
          'is_proxy': 0,
          'caller_id_option': 1,
          'missed_call_handling_mode': 2,
          'missed_call_handling_options': '{"forward_to": "+18189005934", "reroute_to_campaign_id": null}',
          'call_router_behavior': 1,
          'ivr_prompt_tts': 'If you know your extension you can enter it now, if not Press 1 to connect to GoSite.',
          'ivr_prompt_file': null,
          'should_message_if_missed': false,
          'missed_call_message': null,
          'should_block_spam': false,
          'created_at': '2018-02-02 04:37:23',
          'updated_at': '2021-07-08 14:45:01',
          'type': 0,
          'subtype': null,
          'is_fax': false,
          'operating_hours': '{"friday": [{"id": "5", "open": "24hrs", "close": "24hrs", "isOpen": true}], "monday": [{"id": "1", "open": "24hrs", "close": "24hrs", "isOpen": true}], "sunday": [{"id": "7", "open": "24hrs", "close": "24hrs", "isOpen": true}], "tuesday": [{"id": "2", "open": "24hrs", "close": "24hrs", "isOpen": true}], "saturday": [{"id": "6", "open": "24hrs", "close": "24hrs", "isOpen": true}], "thursday": [{"id": "4", "open": "24hrs", "close": "24hrs", "isOpen": true}], "wednesday": [{"id": "3", "open": "24hrs", "close": "24hrs", "isOpen": true}]}',
          'closed_hours_voice_prompt': '{"tts": null, "file": null, "enabled": false}',
          'closed_hours_auto_reply_text': '{"enabled": false, "message": null}',
          'triggers': '[{"id": "52102498-c925-4e93-98d3-d9f56614bfff", "type": "contact", "valid": true, "value": 0, "symbol": null, "tag_ids": [27], "keywords": [], "variable": null, "direction": null, "operation": "tag", "workflow_ids": [], "has_condition": false, "disposition_status": null, "disposition_status_id": []}]',
          'ivr_steps': '[{"id": "2e7f79f3-23f0-4919-b423-b5740e717516", "key": null, "task": "route_to_extension", "type": "normal", "valid": true, "tag_ids": [], "message_tts": null, "message_file": null, "workflow_ids": [], "route_to_user_id": null, "call_router_behavior": 1, "listen_for_extension": true, "reroute_to_campaign_id": null, "route_to_ring_group_id": false, "route_to_destination_id": false}, {"id": "16a2ad16-902c-4b36-97dc-9b38b673bd32", "key": "*", "task": "replay", "type": "normal", "valid": true, "tag_ids": [], "message_tts": null, "message_file": null, "workflow_ids": [], "route_to_user_id": null, "call_router_behavior": null, "listen_for_extension": false, "reroute_to_campaign_id": null, "route_to_ring_group_id": null, "route_to_destination_id": null}, {"id": "e03c5f16-fdb0-4dfd-a1b2-67f09c7ed4fe", "key": null, "task": "replay", "type": "exit", "valid": true, "tag_ids": [], "message_tts": null, "message_file": null, "workflow_ids": [], "route_to_user_id": null, "call_router_behavior": null, "listen_for_extension": false, "reroute_to_campaign_id": null, "route_to_ring_group_id": null}, {"id": "d2828df6-eb04-47d0-bad1-49643c15b82b", "key": "1", "task": "route_to_ring_group", "type": "normal", "valid": true, "tag_ids": [], "message_tts": null, "message_file": null, "workflow_ids": [], "route_to_user_id": null, "call_router_behavior": null, "listen_for_extension": false, "reroute_to_campaign_id": null, "route_to_ring_group_id": 188, "route_to_destination_id": null}]',
          'pool_size': null,
          'pool_options': null,
          'visitor_tracking_mode': null,
          'visitor_tracking_options': null,
          'active': true,
          'tracking_source': null,
          'has_messaging_service': false,
          'dni_script_address': 'https://app.alodev.org/v1/sZwMTAmV/dni.js',
          'incoming_number': '+18583608237',
          'first_incoming_number': {
            'id': 2034,
            'company_id': 7,
            'campaign_id': 10,
            'phone_number': '+18583608237',
            'city': '',
            'state': 'CA',
            'country': 'US',
            'label': 'Vulcan Hotels-incoming number',
            'non_billable': false,
            'is_tollfree': false,
            'is_rented': true,
            'do_not_use': false,
            'is_voice_capable': true,
            'is_fax_capable': true,
            'is_sms_capable': true,
            'is_mms_capable': true,
            'is_fax': false,
            'default_callerid': false,
            'created_at': '2021-05-27 21:33:10',
            'updated_at': '2021-07-08 06:00:09'
          }
        }
      },
      {
        'contacts_count': 0,
        'sequences_count': 1,
        'remaining_tasks': '0',
        'total_tasks': 0,
        'id': 240,
        'company_id': 7,
        'campaign_id': 10,
        'tag_id': null,
        'name': 'ALOPRO-1605',
        'description': null,
        'send_on': 1,
        'open': null,
        'close': null,
        'always_open': true,
        'do_not_enroll_after_hours': false,
        'triggers': null,
        'mailgun_intake_route': null,
        'disenroll_on_response': true,
        'disenroll_on_calls': false,
        'batch_size': 0,
        'active': false,
        'current_status': 1,
        'task_count': 0,
        'is_v2': 0,
        'process_on_holidays': false,
        'created_at': '2021-07-01 23:31:24',
        'process_condition': 'Process everyday<br/> at any time of the day.',
        'converted_open': null,
        'converted_close': null,
        'is_enrollable': true,
        'diagnosis': [{
          'name': 'Company is active',
          'value': true
        }, {
          'name': 'Line is active',
          'value': true
        }, {
          'name': 'Sufficient funds',
          'value': true
        }, {
          'name': 'Has steps',
          'value': true
        }],
        'real_status': 2,
        'campaign': {
          'id': 10,
          'company_id': 7,
          'ring_group_id': 32,
          'ivr_text_ring_group_id': null,
          'user_id': null,
          'default_filter_id': null,
          'name': 'Vulcan Hotel',
          'description': null,
          'should_greet': true,
          'greeting_tts': 'Welcome to Aloware',
          'greeting_file': null,
          'should_ask_for_text_authorization': false,
          'ask_for_text_authorization_tts': 'Press 1 for text message authorization.',
          'ask_for_text_authorization_file': null,
          'should_whisper': true,
          'whisper_tts': 'Hey [AgentName] This is a call from [CampaignName]!',
          'whisper_file': null,
          'should_record': true,
          'record_tts': 'Your call is being recorded for quality assurance purposes.',
          'record_file': null,
          'voicemail_tts': 'We are sorry, but no agents are available to take this call. Please leave your message after the beep.',
          'voicemail_file': null,
          'review_required': 1,
          'review_duration': 60,
          'is_proxy': 0,
          'caller_id_option': 1,
          'missed_call_handling_mode': 2,
          'missed_call_handling_options': '{"forward_to": "+18189005934", "reroute_to_campaign_id": null}',
          'call_router_behavior': 1,
          'ivr_prompt_tts': 'If you know your extension you can enter it now, if not Press 1 to connect to GoSite.',
          'ivr_prompt_file': null,
          'should_message_if_missed': false,
          'missed_call_message': null,
          'should_block_spam': false,
          'created_at': '2018-02-02 04:37:23',
          'updated_at': '2021-07-08 14:45:01',
          'type': 0,
          'subtype': null,
          'is_fax': false,
          'operating_hours': '{"friday": [{"id": "5", "open": "24hrs", "close": "24hrs", "isOpen": true}], "monday": [{"id": "1", "open": "24hrs", "close": "24hrs", "isOpen": true}], "sunday": [{"id": "7", "open": "24hrs", "close": "24hrs", "isOpen": true}], "tuesday": [{"id": "2", "open": "24hrs", "close": "24hrs", "isOpen": true}], "saturday": [{"id": "6", "open": "24hrs", "close": "24hrs", "isOpen": true}], "thursday": [{"id": "4", "open": "24hrs", "close": "24hrs", "isOpen": true}], "wednesday": [{"id": "3", "open": "24hrs", "close": "24hrs", "isOpen": true}]}',
          'closed_hours_voice_prompt': '{"tts": null, "file": null, "enabled": false}',
          'closed_hours_auto_reply_text': '{"enabled": false, "message": null}',
          'triggers': '[{"id": "52102498-c925-4e93-98d3-d9f56614bfff", "type": "contact", "valid": true, "value": 0, "symbol": null, "tag_ids": [27], "keywords": [], "variable": null, "direction": null, "operation": "tag", "workflow_ids": [], "has_condition": false, "disposition_status": null, "disposition_status_id": []}]',
          'ivr_steps': '[{"id": "2e7f79f3-23f0-4919-b423-b5740e717516", "key": null, "task": "route_to_extension", "type": "normal", "valid": true, "tag_ids": [], "message_tts": null, "message_file": null, "workflow_ids": [], "route_to_user_id": null, "call_router_behavior": 1, "listen_for_extension": true, "reroute_to_campaign_id": null, "route_to_ring_group_id": false, "route_to_destination_id": false}, {"id": "16a2ad16-902c-4b36-97dc-9b38b673bd32", "key": "*", "task": "replay", "type": "normal", "valid": true, "tag_ids": [], "message_tts": null, "message_file": null, "workflow_ids": [], "route_to_user_id": null, "call_router_behavior": null, "listen_for_extension": false, "reroute_to_campaign_id": null, "route_to_ring_group_id": null, "route_to_destination_id": null}, {"id": "e03c5f16-fdb0-4dfd-a1b2-67f09c7ed4fe", "key": null, "task": "replay", "type": "exit", "valid": true, "tag_ids": [], "message_tts": null, "message_file": null, "workflow_ids": [], "route_to_user_id": null, "call_router_behavior": null, "listen_for_extension": false, "reroute_to_campaign_id": null, "route_to_ring_group_id": null}, {"id": "d2828df6-eb04-47d0-bad1-49643c15b82b", "key": "1", "task": "route_to_ring_group", "type": "normal", "valid": true, "tag_ids": [], "message_tts": null, "message_file": null, "workflow_ids": [], "route_to_user_id": null, "call_router_behavior": null, "listen_for_extension": false, "reroute_to_campaign_id": null, "route_to_ring_group_id": 188, "route_to_destination_id": null}]',
          'pool_size': null,
          'pool_options': null,
          'visitor_tracking_mode': null,
          'visitor_tracking_options': null,
          'active': true,
          'tracking_source': null,
          'has_messaging_service': false,
          'dni_script_address': 'https://app.alodev.org/v1/sZwMTAmV/dni.js',
          'incoming_number': '+18583608237',
          'first_incoming_number': {
            'id': 2034,
            'company_id': 7,
            'campaign_id': 10,
            'phone_number': '+18583608237',
            'city': '',
            'state': 'CA',
            'country': 'US',
            'label': 'Vulcan Hotels-incoming number',
            'non_billable': false,
            'is_tollfree': false,
            'is_rented': true,
            'do_not_use': false,
            'is_voice_capable': true,
            'is_fax_capable': true,
            'is_sms_capable': true,
            'is_mms_capable': true,
            'is_fax': false,
            'default_callerid': false,
            'created_at': '2021-05-27 21:33:10',
            'updated_at': '2021-07-08 06:00:09'
          }
        }
      },
      {
        'contacts_count': 0,
        'sequences_count': 1,
        'remaining_tasks': '0',
        'total_tasks': 0,
        'id': 216,
        'company_id': 7,
        'campaign_id': 511,
        'tag_id': null,
        'name': "Chap's Sequence",
        'description': null,
        'send_on': 1,
        'open': null,
        'close': null,
        'always_open': true,
        'do_not_enroll_after_hours': false,
        'triggers': null,
        'mailgun_intake_route': null,
        'disenroll_on_response': true,
        'disenroll_on_calls': false,
        'batch_size': 20,
        'active': true,
        'current_status': 1,
        'task_count': 0,
        'is_v2': 1,
        'process_on_holidays': false,
        'created_at': '2021-06-04 21:34:53',
        'process_condition': 'Process everyday<br/> at any time of the day.',
        'converted_open': null,
        'converted_close': null,
        'is_enrollable': true,
        'diagnosis': [{
          'name': 'Company is active',
          'value': true
        }, {
          'name': 'Line is active',
          'value': true
        }, {
          'name': 'Sufficient funds',
          'value': true
        }, {
          'name': 'Has steps',
          'value': true
        }],
        'real_status': 2,
        'campaign': {
          'id': 511,
          'company_id': 7,
          'ring_group_id': null,
          'ivr_text_ring_group_id': null,
          'user_id': 702,
          'default_filter_id': null,
          'name': 'Edison Line',
          'description': null,
          'should_greet': false,
          'greeting_tts': ' ',
          'greeting_file': null,
          'should_ask_for_text_authorization': false,
          'ask_for_text_authorization_tts': 'Press 1 for text message authorization.',
          'ask_for_text_authorization_file': null,
          'should_whisper': false,
          'whisper_tts': ' ',
          'whisper_file': null,
          'should_record': false,
          'record_tts': ' ',
          'record_file': null,
          'voicemail_tts': 'We are sorry, but no agents are available to take this call. Please leave your message after the beep.',
          'voicemail_file': null,
          'review_required': 0,
          'review_duration': 60,
          'is_proxy': 0,
          'caller_id_option': 0,
          'missed_call_handling_mode': 1,
          'missed_call_handling_options': null,
          'call_router_behavior': 1,
          'ivr_prompt_tts': ' ',
          'ivr_prompt_file': null,
          'should_message_if_missed': false,
          'missed_call_message': null,
          'should_block_spam': false,
          'created_at': '2021-05-05 23:39:08',
          'updated_at': '2021-05-06 23:33:08',
          'type': 0,
          'subtype': null,
          'is_fax': false,
          'operating_hours': '{"friday": [{"id": "5", "open": "24hrs", "close": "24hrs", "isOpen": true}], "monday": [{"id": "1", "open": "24hrs", "close": "24hrs", "isOpen": true}], "sunday": [{"id": "7", "open": "24hrs", "close": "24hrs", "isOpen": true}], "tuesday": [{"id": "2", "open": "24hrs", "close": "24hrs", "isOpen": true}], "saturday": [{"id": "6", "open": "24hrs", "close": "24hrs", "isOpen": true}], "thursday": [{"id": "4", "open": "24hrs", "close": "24hrs", "isOpen": true}], "wednesday": [{"id": "3", "open": "24hrs", "close": "24hrs", "isOpen": true}]}',
          'closed_hours_voice_prompt': '{"tts": null, "file": null, "enabled": false}',
          'closed_hours_auto_reply_text': '{"enabled": false, "message": null}',
          'triggers': '[]',
          'ivr_steps': '[{"id": "36affd41-7033-489e-97a0-c0c2f3c5d437", "key": null, "task": "replay", "type": "exit", "valid": true, "tag_ids": [], "message_tts": null, "message_file": null, "workflow_ids": [], "route_to_user_id": null, "call_router_behavior": null, "listen_for_extension": false, "reroute_to_campaign_id": null, "route_to_ring_group_id": null}]',
          'pool_size': null,
          'pool_options': null,
          'visitor_tracking_mode': null,
          'visitor_tracking_options': null,
          'active': true,
          'tracking_source': null,
          'has_messaging_service': false,
          'dni_script_address': 'https://app.alodev.org/v1/sZwMTAmV/dni.js',
          'incoming_number': '+16575000893',
          'first_incoming_number': {
            'id': 2030,
            'company_id': 7,
            'campaign_id': 511,
            'phone_number': '+16575000893',
            'city': '',
            'state': 'CA',
            'country': 'US',
            'label': 'Edison Line-incoming number',
            'non_billable': false,
            'is_tollfree': false,
            'is_rented': true,
            'do_not_use': false,
            'is_voice_capable': true,
            'is_fax_capable': true,
            'is_sms_capable': true,
            'is_mms_capable': true,
            'is_fax': false,
            'default_callerid': false,
            'created_at': '2021-05-05 23:39:09',
            'updated_at': '2021-07-05 18:58:30'
          }
        }
      },
      {
        'contacts_count': 0,
        'sequences_count': 2,
        'remaining_tasks': '0',
        'total_tasks': 0,
        'id': 199,
        'company_id': 7,
        'campaign_id': 508,
        'tag_id': null,
        'name': 'test sequence',
        'description': null,
        'send_on': 0,
        'open': '01:00:00',
        'close': '09:00:00',
        'always_open': true,
        'do_not_enroll_after_hours': false,
        'triggers': '[{"id": "29dacc9c-48fe-45f7-8f1c-471bef25f293", "type": "disposition", "valid": true, "enroll_action": "enroll", "disposition_status_id": 133}, {"id": "a59646d8-23fd-4f1c-9b47-c3950cffaf11", "type": "call disposition", "valid": true, "enroll_action": "enroll", "call_disposition_id": 15}, {"id": "b29e9624-798d-472e-8416-715edbc90f85", "type": 1, "valid": true, "value": 0, "symbol": ">=", "variable": "duration", "direction": 2, "operation": "disenroll", "has_condition": true, "disposition_status": 8}]',
        'mailgun_intake_route': null,
        'disenroll_on_response': true,
        'disenroll_on_calls': true,
        'batch_size': 20,
        'active': false,
        'current_status': 3,
        'task_count': 61,
        'is_v2': 0,
        'process_on_holidays': false,
        'created_at': '2021-04-14 21:13:23',
        'process_condition': 'Process on business days<br/> at any time of the day.',
        'converted_open': '18:00:00',
        'converted_close': '02:00:00',
        'is_enrollable': true,
        'diagnosis': [{
          'name': 'Company is active',
          'value': true
        }, {
          'name': 'Line is active',
          'value': true
        }, {
          'name': 'Sufficient funds',
          'value': true
        }, {
          'name': 'Has steps',
          'value': true
        }],
        'real_status': 2,
        'campaign': {
          'id': 508,
          'company_id': 7,
          'ring_group_id': null,
          'ivr_text_ring_group_id': null,
          'user_id': 687,
          'default_filter_id': null,
          'name': 'Skyler Personal Line',
          'description': null,
          'should_greet': false,
          'greeting_tts': null,
          'greeting_file': null,
          'should_ask_for_text_authorization': false,
          'ask_for_text_authorization_tts': null,
          'ask_for_text_authorization_file': null,
          'should_whisper': false,
          'whisper_tts': null,
          'whisper_file': null,
          'should_record': false,
          'record_tts': null,
          'record_file': null,
          'voicemail_tts': 'We are sorry, but no agents are available to take this call. Please leave your message after the beep.',
          'voicemail_file': null,
          'review_required': 0,
          'review_duration': 60,
          'is_proxy': 0,
          'caller_id_option': 0,
          'missed_call_handling_mode': 1,
          'missed_call_handling_options': null,
          'call_router_behavior': 1,
          'ivr_prompt_tts': null,
          'ivr_prompt_file': null,
          'should_message_if_missed': false,
          'missed_call_message': null,
          'should_block_spam': false,
          'created_at': '2021-03-24 20:56:30',
          'updated_at': '2021-03-24 20:56:33',
          'type': 0,
          'subtype': null,
          'is_fax': false,
          'operating_hours': '{"friday": [{"id": "5", "open": "24hrs", "close": "24hrs", "isOpen": true}], "monday": [{"id": "1", "open": "24hrs", "close": "24hrs", "isOpen": true}], "sunday": [{"id": "7", "open": "24hrs", "close": "24hrs", "isOpen": true}], "tuesday": [{"id": "2", "open": "24hrs", "close": "24hrs", "isOpen": true}], "saturday": [{"id": "6", "open": "24hrs", "close": "24hrs", "isOpen": true}], "thursday": [{"id": "4", "open": "24hrs", "close": "24hrs", "isOpen": true}], "wednesday": [{"id": "3", "open": "24hrs", "close": "24hrs", "isOpen": true}]}',
          'closed_hours_voice_prompt': '{"tts": null, "file": null, "enabled": false}',
          'closed_hours_auto_reply_text': '{"enabled": false, "message": null}',
          'triggers': null,
          'ivr_steps': null,
          'pool_size': null,
          'pool_options': null,
          'visitor_tracking_mode': null,
          'visitor_tracking_options': null,
          'active': true,
          'tracking_source': null,
          'has_messaging_service': false,
          'dni_script_address': 'https://app.alodev.org/v1/sZwMTAmV/dni.js',
          'incoming_number': '+14353343884',
          'first_incoming_number': {
            'id': 2027,
            'company_id': 7,
            'campaign_id': 508,
            'phone_number': '+14353343884',
            'city': '',
            'state': 'UT',
            'country': 'US',
            'label': 'Skyler Personal Line-incoming number',
            'non_billable': false,
            'is_tollfree': false,
            'is_rented': true,
            'do_not_use': false,
            'is_voice_capable': true,
            'is_fax_capable': true,
            'is_sms_capable': true,
            'is_mms_capable': true,
            'is_fax': false,
            'default_callerid': false,
            'created_at': '2021-03-24 20:56:32',
            'updated_at': '2021-07-07 20:59:05'
          }
        }
      },
      {
        'contacts_count': 0,
        'sequences_count': 2,
        'remaining_tasks': '0',
        'total_tasks': 0,
        'id': 198,
        'company_id': 7,
        'campaign_id': 10,
        'tag_id': null,
        'name': 'Test Sequence by Janssen',
        'description': null,
        'send_on': 1,
        'open': '01:00:00',
        'close': '09:00:00',
        'always_open': true,
        'do_not_enroll_after_hours': false,
        'triggers': '[{"id": "a2d21a1f-6d4e-4477-bb62-898a288aa44a", "type": "disposition", "valid": true, "enroll_action": "enroll", "disposition_status_id": 130}]',
        'mailgun_intake_route': 'twilio-dev-198@intake.alodev.org',
        'disenroll_on_response': true,
        'disenroll_on_calls': false,
        'batch_size': 20,
        'active': true,
        'current_status': 1,
        'task_count': 0,
        'is_v2': 1,
        'process_on_holidays': true,
        'created_at': '2021-04-13 15:19:43',
        'process_condition': 'Process everyday<br/> at any time of the day.',
        'converted_open': '18:00:00',
        'converted_close': '02:00:00',
        'is_enrollable': true,
        'diagnosis': [{
          'name': 'Company is active',
          'value': true
        }, {
          'name': 'Line is active',
          'value': true
        }, {
          'name': 'Sufficient funds',
          'value': true
        }, {
          'name': 'Has steps',
          'value': true
        }],
        'real_status': 2,
        'campaign': {
          'id': 10,
          'company_id': 7,
          'ring_group_id': 32,
          'ivr_text_ring_group_id': null,
          'user_id': null,
          'default_filter_id': null,
          'name': 'Vulcan Hotel',
          'description': null,
          'should_greet': true,
          'greeting_tts': 'Welcome to Aloware',
          'greeting_file': null,
          'should_ask_for_text_authorization': false,
          'ask_for_text_authorization_tts': 'Press 1 for text message authorization.',
          'ask_for_text_authorization_file': null,
          'should_whisper': true,
          'whisper_tts': 'Hey [AgentName] This is a call from [CampaignName]!',
          'whisper_file': null,
          'should_record': true,
          'record_tts': 'Your call is being recorded for quality assurance purposes.',
          'record_file': null,
          'voicemail_tts': 'We are sorry, but no agents are available to take this call. Please leave your message after the beep.',
          'voicemail_file': null,
          'review_required': 1,
          'review_duration': 60,
          'is_proxy': 0,
          'caller_id_option': 1,
          'missed_call_handling_mode': 2,
          'missed_call_handling_options': '{"forward_to": "+18189005934", "reroute_to_campaign_id": null}',
          'call_router_behavior': 1,
          'ivr_prompt_tts': 'If you know your extension you can enter it now, if not Press 1 to connect to GoSite.',
          'ivr_prompt_file': null,
          'should_message_if_missed': false,
          'missed_call_message': null,
          'should_block_spam': false,
          'created_at': '2018-02-02 04:37:23',
          'updated_at': '2021-07-08 14:45:01',
          'type': 0,
          'subtype': null,
          'is_fax': false,
          'operating_hours': '{"friday": [{"id": "5", "open": "24hrs", "close": "24hrs", "isOpen": true}], "monday": [{"id": "1", "open": "24hrs", "close": "24hrs", "isOpen": true}], "sunday": [{"id": "7", "open": "24hrs", "close": "24hrs", "isOpen": true}], "tuesday": [{"id": "2", "open": "24hrs", "close": "24hrs", "isOpen": true}], "saturday": [{"id": "6", "open": "24hrs", "close": "24hrs", "isOpen": true}], "thursday": [{"id": "4", "open": "24hrs", "close": "24hrs", "isOpen": true}], "wednesday": [{"id": "3", "open": "24hrs", "close": "24hrs", "isOpen": true}]}',
          'closed_hours_voice_prompt': '{"tts": null, "file": null, "enabled": false}',
          'closed_hours_auto_reply_text': '{"enabled": false, "message": null}',
          'triggers': '[{"id": "52102498-c925-4e93-98d3-d9f56614bfff", "type": "contact", "valid": true, "value": 0, "symbol": null, "tag_ids": [27], "keywords": [], "variable": null, "direction": null, "operation": "tag", "workflow_ids": [], "has_condition": false, "disposition_status": null, "disposition_status_id": []}]',
          'ivr_steps': '[{"id": "2e7f79f3-23f0-4919-b423-b5740e717516", "key": null, "task": "route_to_extension", "type": "normal", "valid": true, "tag_ids": [], "message_tts": null, "message_file": null, "workflow_ids": [], "route_to_user_id": null, "call_router_behavior": 1, "listen_for_extension": true, "reroute_to_campaign_id": null, "route_to_ring_group_id": false, "route_to_destination_id": false}, {"id": "16a2ad16-902c-4b36-97dc-9b38b673bd32", "key": "*", "task": "replay", "type": "normal", "valid": true, "tag_ids": [], "message_tts": null, "message_file": null, "workflow_ids": [], "route_to_user_id": null, "call_router_behavior": null, "listen_for_extension": false, "reroute_to_campaign_id": null, "route_to_ring_group_id": null, "route_to_destination_id": null}, {"id": "e03c5f16-fdb0-4dfd-a1b2-67f09c7ed4fe", "key": null, "task": "replay", "type": "exit", "valid": true, "tag_ids": [], "message_tts": null, "message_file": null, "workflow_ids": [], "route_to_user_id": null, "call_router_behavior": null, "listen_for_extension": false, "reroute_to_campaign_id": null, "route_to_ring_group_id": null}, {"id": "d2828df6-eb04-47d0-bad1-49643c15b82b", "key": "1", "task": "route_to_ring_group", "type": "normal", "valid": true, "tag_ids": [], "message_tts": null, "message_file": null, "workflow_ids": [], "route_to_user_id": null, "call_router_behavior": null, "listen_for_extension": false, "reroute_to_campaign_id": null, "route_to_ring_group_id": 188, "route_to_destination_id": null}]',
          'pool_size': null,
          'pool_options': null,
          'visitor_tracking_mode': null,
          'visitor_tracking_options': null,
          'active': true,
          'tracking_source': null,
          'has_messaging_service': false,
          'dni_script_address': 'https://app.alodev.org/v1/sZwMTAmV/dni.js',
          'incoming_number': '+18583608237',
          'first_incoming_number': {
            'id': 2034,
            'company_id': 7,
            'campaign_id': 10,
            'phone_number': '+18583608237',
            'city': '',
            'state': 'CA',
            'country': 'US',
            'label': 'Vulcan Hotels-incoming number',
            'non_billable': false,
            'is_tollfree': false,
            'is_rented': true,
            'do_not_use': false,
            'is_voice_capable': true,
            'is_fax_capable': true,
            'is_sms_capable': true,
            'is_mms_capable': true,
            'is_fax': false,
            'default_callerid': false,
            'created_at': '2021-05-27 21:33:10',
            'updated_at': '2021-07-08 06:00:09'
          }
        }
      },
      {
        'contacts_count': 0,
        'sequences_count': 6,
        'remaining_tasks': '0',
        'total_tasks': 0,
        'id': 195,
        'company_id': 7,
        'campaign_id': 434,
        'tag_id': null,
        'name': 'Josiah Test Sequence Run on Holidays',
        'description': null,
        'send_on': 1,
        'open': null,
        'close': null,
        'always_open': true,
        'do_not_enroll_after_hours': false,
        'triggers': '[]',
        'mailgun_intake_route': null,
        'disenroll_on_response': true,
        'disenroll_on_calls': false,
        'batch_size': 20,
        'active': false,
        'current_status': 1,
        'task_count': 18,
        'is_v2': 1,
        'process_on_holidays': true,
        'created_at': '2021-04-06 04:52:52',
        'process_condition': 'Process everyday<br/> at any time of the day.',
        'converted_open': null,
        'converted_close': null,
        'is_enrollable': true,
        'diagnosis': [{
          'name': 'Company is active',
          'value': true
        }, {
          'name': 'Line is active',
          'value': true
        }, {
          'name': 'Sufficient funds',
          'value': true
        }, {
          'name': 'Has steps',
          'value': true
        }],
        'real_status': 2,
        'campaign': {
          'id': 434,
          'company_id': 7,
          'ring_group_id': null,
          'ivr_text_ring_group_id': null,
          'user_id': 618,
          'default_filter_id': null,
          'name': 'Josiah Personal Line 2',
          'description': null,
          'should_greet': false,
          'greeting_tts': ' ',
          'greeting_file': null,
          'should_ask_for_text_authorization': false,
          'ask_for_text_authorization_tts': 'Press 1 for text message authorization.',
          'ask_for_text_authorization_file': null,
          'should_whisper': false,
          'whisper_tts': ' ',
          'whisper_file': null,
          'should_record': false,
          'record_tts': ' ',
          'record_file': null,
          'voicemail_tts': 'We are sorry, but no agents are available to take this call. Please leave your message after the beep.',
          'voicemail_file': null,
          'review_required': 0,
          'review_duration': 60,
          'is_proxy': 0,
          'caller_id_option': 0,
          'missed_call_handling_mode': 1,
          'missed_call_handling_options': '{"forward_to": "", "reroute_to_campaign_id": ""}',
          'call_router_behavior': 1,
          'ivr_prompt_tts': ' ',
          'ivr_prompt_file': null,
          'should_message_if_missed': false,
          'missed_call_message': null,
          'should_block_spam': false,
          'created_at': '2020-06-01 22:02:25',
          'updated_at': '2021-07-07 22:53:37',
          'type': 0,
          'subtype': null,
          'is_fax': false,
          'operating_hours': '{"friday": [{"id": "5", "open": "24hrs", "close": "24hrs", "isOpen": true}], "monday": [{"id": "1", "open": "24hrs", "close": "24hrs", "isOpen": true}], "sunday": [{"id": "7", "open": "24hrs", "close": "24hrs", "isOpen": true}], "tuesday": [{"id": "2", "open": "24hrs", "close": "24hrs", "isOpen": true}], "saturday": [{"id": "6", "open": "24hrs", "close": "24hrs", "isOpen": true}], "thursday": [{"id": "4", "open": "24hrs", "close": "24hrs", "isOpen": true}], "wednesday": [{"id": "3", "open": "24hrs", "close": "24hrs", "isOpen": true}]}',
          'closed_hours_voice_prompt': '{"tts": null, "file": null, "enabled": false}',
          'closed_hours_auto_reply_text': '{"enabled": false, "message": null}',
          'triggers': '[]',
          'ivr_steps': '[{"id": "bd0e2f1a-00b9-4120-a7b8-c02c28aad827", "key": null, "task": "replay", "type": "exit", "valid": true, "tag_ids": [], "message_tts": null, "message_file": null, "workflow_ids": [], "route_to_user_id": null, "call_router_behavior": null, "listen_for_extension": false, "reroute_to_campaign_id": null, "route_to_ring_group_id": null}]',
          'pool_size': null,
          'pool_options': null,
          'visitor_tracking_mode': null,
          'visitor_tracking_options': null,
          'active': true,
          'tracking_source': null,
          'has_messaging_service': false,
          'dni_script_address': 'https://app.alodev.org/v1/sZwMTAmV/dni.js',
          'incoming_number': '+18185923225',
          'first_incoming_number': {
            'id': 452,
            'company_id': 7,
            'campaign_id': 434,
            'phone_number': '+18185923225',
            'city': '',
            'state': 'CA',
            'country': 'US',
            'label': 'Jeram Personal Line-incoming number',
            'non_billable': false,
            'is_tollfree': false,
            'is_rented': true,
            'do_not_use': false,
            'is_voice_capable': true,
            'is_fax_capable': true,
            'is_sms_capable': true,
            'is_mms_capable': true,
            'is_fax': false,
            'default_callerid': false,
            'created_at': '2020-06-01 22:02:27',
            'updated_at': '2021-06-22 01:22:35'
          }
        }
      },
      {
        'contacts_count': 0,
        'sequences_count': 1,
        'remaining_tasks': '0',
        'total_tasks': 0,
        'id': 191,
        'company_id': 7,
        'campaign_id': 10,
        'tag_id': null,
        'name': 'Facebook Leads',
        'description': null,
        'send_on': 0,
        'open': null,
        'close': null,
        'always_open': true,
        'do_not_enroll_after_hours': false,
        'triggers': null,
        'mailgun_intake_route': null,
        'disenroll_on_response': false,
        'disenroll_on_calls': false,
        'batch_size': 20,
        'active': false,
        'current_status': 1,
        'task_count': 0,
        'is_v2': 0,
        'process_on_holidays': false,
        'created_at': '2021-03-30 17:21:49',
        'process_condition': 'Process on business days<br/> at any time of the day.',
        'converted_open': null,
        'converted_close': null,
        'is_enrollable': true,
        'diagnosis': [{
          'name': 'Company is active',
          'value': true
        }, {
          'name': 'Line is active',
          'value': true
        }, {
          'name': 'Sufficient funds',
          'value': true
        }, {
          'name': 'Has steps',
          'value': true
        }],
        'real_status': 2,
        'campaign': {
          'id': 10,
          'company_id': 7,
          'ring_group_id': 32,
          'ivr_text_ring_group_id': null,
          'user_id': null,
          'default_filter_id': null,
          'name': 'Vulcan Hotel',
          'description': null,
          'should_greet': true,
          'greeting_tts': 'Welcome to Aloware',
          'greeting_file': null,
          'should_ask_for_text_authorization': false,
          'ask_for_text_authorization_tts': 'Press 1 for text message authorization.',
          'ask_for_text_authorization_file': null,
          'should_whisper': true,
          'whisper_tts': 'Hey [AgentName] This is a call from [CampaignName]!',
          'whisper_file': null,
          'should_record': true,
          'record_tts': 'Your call is being recorded for quality assurance purposes.',
          'record_file': null,
          'voicemail_tts': 'We are sorry, but no agents are available to take this call. Please leave your message after the beep.',
          'voicemail_file': null,
          'review_required': 1,
          'review_duration': 60,
          'is_proxy': 0,
          'caller_id_option': 1,
          'missed_call_handling_mode': 2,
          'missed_call_handling_options': '{"forward_to": "+18189005934", "reroute_to_campaign_id": null}',
          'call_router_behavior': 1,
          'ivr_prompt_tts': 'If you know your extension you can enter it now, if not Press 1 to connect to GoSite.',
          'ivr_prompt_file': null,
          'should_message_if_missed': false,
          'missed_call_message': null,
          'should_block_spam': false,
          'created_at': '2018-02-02 04:37:23',
          'updated_at': '2021-07-08 14:45:01',
          'type': 0,
          'subtype': null,
          'is_fax': false,
          'operating_hours': '{"friday": [{"id": "5", "open": "24hrs", "close": "24hrs", "isOpen": true}], "monday": [{"id": "1", "open": "24hrs", "close": "24hrs", "isOpen": true}], "sunday": [{"id": "7", "open": "24hrs", "close": "24hrs", "isOpen": true}], "tuesday": [{"id": "2", "open": "24hrs", "close": "24hrs", "isOpen": true}], "saturday": [{"id": "6", "open": "24hrs", "close": "24hrs", "isOpen": true}], "thursday": [{"id": "4", "open": "24hrs", "close": "24hrs", "isOpen": true}], "wednesday": [{"id": "3", "open": "24hrs", "close": "24hrs", "isOpen": true}]}',
          'closed_hours_voice_prompt': '{"tts": null, "file": null, "enabled": false}',
          'closed_hours_auto_reply_text': '{"enabled": false, "message": null}',
          'triggers': '[{"id": "52102498-c925-4e93-98d3-d9f56614bfff", "type": "contact", "valid": true, "value": 0, "symbol": null, "tag_ids": [27], "keywords": [], "variable": null, "direction": null, "operation": "tag", "workflow_ids": [], "has_condition": false, "disposition_status": null, "disposition_status_id": []}]',
          'ivr_steps': '[{"id": "2e7f79f3-23f0-4919-b423-b5740e717516", "key": null, "task": "route_to_extension", "type": "normal", "valid": true, "tag_ids": [], "message_tts": null, "message_file": null, "workflow_ids": [], "route_to_user_id": null, "call_router_behavior": 1, "listen_for_extension": true, "reroute_to_campaign_id": null, "route_to_ring_group_id": false, "route_to_destination_id": false}, {"id": "16a2ad16-902c-4b36-97dc-9b38b673bd32", "key": "*", "task": "replay", "type": "normal", "valid": true, "tag_ids": [], "message_tts": null, "message_file": null, "workflow_ids": [], "route_to_user_id": null, "call_router_behavior": null, "listen_for_extension": false, "reroute_to_campaign_id": null, "route_to_ring_group_id": null, "route_to_destination_id": null}, {"id": "e03c5f16-fdb0-4dfd-a1b2-67f09c7ed4fe", "key": null, "task": "replay", "type": "exit", "valid": true, "tag_ids": [], "message_tts": null, "message_file": null, "workflow_ids": [], "route_to_user_id": null, "call_router_behavior": null, "listen_for_extension": false, "reroute_to_campaign_id": null, "route_to_ring_group_id": null}, {"id": "d2828df6-eb04-47d0-bad1-49643c15b82b", "key": "1", "task": "route_to_ring_group", "type": "normal", "valid": true, "tag_ids": [], "message_tts": null, "message_file": null, "workflow_ids": [], "route_to_user_id": null, "call_router_behavior": null, "listen_for_extension": false, "reroute_to_campaign_id": null, "route_to_ring_group_id": 188, "route_to_destination_id": null}]',
          'pool_size': null,
          'pool_options': null,
          'visitor_tracking_mode': null,
          'visitor_tracking_options': null,
          'active': true,
          'tracking_source': null,
          'has_messaging_service': false,
          'dni_script_address': 'https://app.alodev.org/v1/sZwMTAmV/dni.js',
          'incoming_number': '+18583608237',
          'first_incoming_number': {
            'id': 2034,
            'company_id': 7,
            'campaign_id': 10,
            'phone_number': '+18583608237',
            'city': '',
            'state': 'CA',
            'country': 'US',
            'label': 'Vulcan Hotels-incoming number',
            'non_billable': false,
            'is_tollfree': false,
            'is_rented': true,
            'do_not_use': false,
            'is_voice_capable': true,
            'is_fax_capable': true,
            'is_sms_capable': true,
            'is_mms_capable': true,
            'is_fax': false,
            'default_callerid': false,
            'created_at': '2021-05-27 21:33:10',
            'updated_at': '2021-07-08 06:00:09'
          }
        }
      },
      {
        'contacts_count': 0,
        'sequences_count': 0,
        'remaining_tasks': '0',
        'total_tasks': 0,
        'id': 181,
        'company_id': 7,
        'campaign_id': 486,
        'tag_id': null,
        'name': 'QA Sequence (DO NOT DELETE)',
        'description': 'test',
        'send_on': 0,
        'open': '01:00:00',
        'close': '09:00:00',
        'always_open': false,
        'do_not_enroll_after_hours': false,
        'triggers': null,
        'mailgun_intake_route': null,
        'disenroll_on_response': true,
        'disenroll_on_calls': true,
        'batch_size': 20,
        'active': true,
        'current_status': 4,
        'task_count': 0,
        'is_v2': 0,
        'process_on_holidays': false,
        'created_at': '2021-03-02 04:32:38',
        'process_condition': 'Process on business days<br/> at 6:00 pm to 2:00 am',
        'converted_open': '18:00:00',
        'converted_close': '02:00:00',
        'is_enrollable': true,
        'diagnosis': [{
          'name': 'Company is active',
          'value': true
        }, {
          'name': 'Line is active',
          'value': true
        }, {
          'name': 'Sufficient funds',
          'value': true
        }, {
          'name': 'Has steps',
          'value': false
        }],
        'real_status': 3,
        'campaign': {
          'id': 486,
          'company_id': 7,
          'ring_group_id': null,
          'ivr_text_ring_group_id': null,
          'user_id': null,
          'default_filter_id': null,
          'name': '+12283357741',
          'description': null,
          'should_greet': false,
          'greeting_tts': '-',
          'greeting_file': null,
          'should_ask_for_text_authorization': false,
          'ask_for_text_authorization_tts': null,
          'ask_for_text_authorization_file': null,
          'should_whisper': false,
          'whisper_tts': '-',
          'whisper_file': null,
          'should_record': false,
          'record_tts': '-',
          'record_file': null,
          'voicemail_tts': 'We are sorry, but no agents are available to take this call. Please leave your message after the beep.',
          'voicemail_file': null,
          'review_required': 0,
          'review_duration': 60,
          'is_proxy': 0,
          'caller_id_option': 0,
          'missed_call_handling_mode': 1,
          'missed_call_handling_options': '{"forward_to": "", "reroute_to_campaign_id": ""}',
          'call_router_behavior': 3,
          'ivr_prompt_tts': null,
          'ivr_prompt_file': null,
          'should_message_if_missed': false,
          'missed_call_message': null,
          'should_block_spam': false,
          'created_at': '2020-12-16 00:30:26',
          'updated_at': '2021-07-06 23:20:46',
          'type': 0,
          'subtype': null,
          'is_fax': false,
          'operating_hours': '{"friday": [{"id": "5", "open": "24hrs", "close": "24hrs", "isOpen": true}], "monday": [{"id": "1", "open": "24hrs", "close": "24hrs", "isOpen": true}], "sunday": [{"id": "7", "open": "24hrs", "close": "24hrs", "isOpen": true}], "tuesday": [{"id": "2", "open": "24hrs", "close": "24hrs", "isOpen": true}], "saturday": [{"id": "6", "open": "24hrs", "close": "24hrs", "isOpen": true}], "thursday": [{"id": "4", "open": "24hrs", "close": "24hrs", "isOpen": true}], "wednesday": [{"id": "3", "open": "24hrs", "close": "24hrs", "isOpen": true}]}',
          'closed_hours_voice_prompt': '{"tts": null, "file": null, "enabled": false}',
          'closed_hours_auto_reply_text': '{"enabled": false, "message": null}',
          'triggers': null,
          'ivr_steps': null,
          'pool_size': null,
          'pool_options': null,
          'visitor_tracking_mode': null,
          'visitor_tracking_options': null,
          'active': true,
          'tracking_source': null,
          'has_messaging_service': false,
          'dni_script_address': 'https://app.alodev.org/v1/sZwMTAmV/dni.js',
          'incoming_number': null,
          'first_incoming_number': null
        }
      },
      {
        'contacts_count': 0,
        'sequences_count': 2,
        'remaining_tasks': '0',
        'total_tasks': 0,
        'id': 177,
        'company_id': 7,
        'campaign_id': 11,
        'tag_id': null,
        'name': 'ADF/XML',
        'description': null,
        'send_on': 0,
        'open': '17:00:00',
        'close': '01:00:00',
        'always_open': false,
        'do_not_enroll_after_hours': false,
        'triggers': '[{"id": "a2617bf5-1c63-4977-8dda-de49e46c6b1e", "type": "disposition", "valid": true, "enroll_action": "disenroll", "disposition_status_id": 34}]',
        'mailgun_intake_route': 'twilio-dev-177@intake.alodev.org',
        'disenroll_on_response': true,
        'disenroll_on_calls': false,
        'batch_size': 20,
        'active': true,
        'current_status': 1,
        'task_count': 31,
        'is_v2': 1,
        'process_on_holidays': false,
        'created_at': '2021-01-09 01:01:39',
        'process_condition': 'Process on business days<br/> at 10:00 am to 6:00 pm',
        'converted_open': '10:00:00',
        'converted_close': '18:00:00',
        'is_enrollable': true,
        'diagnosis': [{
          'name': 'Company is active',
          'value': true
        }, {
          'name': 'Line is active',
          'value': true
        }, {
          'name': 'Sufficient funds',
          'value': true
        }, {
          'name': 'Has steps',
          'value': true
        }],
        'real_status': 2,
        'campaign': {
          'id': 11,
          'company_id': 7,
          'ring_group_id': null,
          'ivr_text_ring_group_id': null,
          'user_id': 6,
          'default_filter_id': null,
          'name': 'Federation HQ',
          'description': null,
          'should_greet': true,
          'greeting_tts': 'Hi! Thanks for calling Zynpass Dev.',
          'greeting_file': null,
          'should_ask_for_text_authorization': false,
          'ask_for_text_authorization_tts': 'Press 1 for text message authorization.',
          'ask_for_text_authorization_file': null,
          'should_whisper': true,
          'whisper_tts': 'This is a call from [LineName]',
          'whisper_file': null,
          'should_record': true,
          'record_tts': 'This call may be recorded or monitored for quality assurance purposes.',
          'record_file': null,
          'voicemail_tts': 'We are sorry, but no agents are available to take this call. Please leave your message after the beep.',
          'voicemail_file': null,
          'review_required': 1,
          'review_duration': 60,
          'is_proxy': 0,
          'caller_id_option': 0,
          'missed_call_handling_mode': 1,
          'missed_call_handling_options': '{"forward_to": "+18184059107"}',
          'call_router_behavior': 1,
          'ivr_prompt_tts': 'If you know the extension of the party you are trying to reach, you may dial it at any time, If not, press one for sales. press two for support.',
          'ivr_prompt_file': null,
          'should_message_if_missed': false,
          'missed_call_message': null,
          'should_block_spam': false,
          'created_at': '2018-02-02 04:37:48',
          'updated_at': '2021-07-08 05:27:06',
          'type': 0,
          'subtype': null,
          'is_fax': false,
          'operating_hours': '{"friday": [{"id": "5", "open": "24hrs", "close": "24hrs", "isOpen": true}], "monday": [{"id": "1", "open": "24hrs", "close": "24hrs", "isOpen": true}], "sunday": [{"id": "7", "open": null, "close": null, "isOpen": false}], "tuesday": [{"id": "2", "open": "24hrs", "close": "24hrs", "isOpen": true}], "saturday": [{"id": "6", "open": "24hrs", "close": "24hrs", "isOpen": true}], "thursday": [{"id": "4", "open": "24hrs", "close": "24hrs", "isOpen": true}], "wednesday": [{"id": "3", "open": "24hrs", "close": "24hrs", "isOpen": true}]}',
          'closed_hours_voice_prompt': '{"tts": "Sorry, we are closed at this time.", "file": null, "enabled": true}',
          'closed_hours_auto_reply_text': '{"enabled": false, "message": "Sorry, we are closed at this time."}',
          'triggers': '[]',
          'ivr_steps': '[{"id": "8fb837ef-62c4-4247-8916-0c46eb002bae", "key": null, "task": "route_to_extension", "type": "normal", "valid": true, "tag_ids": [], "message_tts": null, "message_file": null, "workflow_ids": [], "route_to_user_id": null, "call_router_behavior": null, "listen_for_extension": true, "reroute_to_campaign_id": null, "route_to_ring_group_id": null}, {"id": "189eea7b-52a0-42f9-99dd-5875841f84bc", "key": null, "task": "replay", "type": "exit", "valid": true, "tag_ids": [], "message_tts": null, "message_file": null, "workflow_ids": [], "route_to_user_id": null, "call_router_behavior": null, "listen_for_extension": false, "reroute_to_campaign_id": null, "route_to_ring_group_id": null}, {"id": "3fa1241f-ff18-46b5-809e-388ad66594be", "key": "1", "task": "route_to_user", "type": "normal", "valid": true, "tag_ids": [], "message_tts": null, "message_file": null, "workflow_ids": [], "route_to_user_id": 6, "call_router_behavior": null, "listen_for_extension": false, "reroute_to_campaign_id": null, "route_to_ring_group_id": null}, {"id": "62b93cb4-9fc9-4fac-86a6-55dc719dc926", "key": "2", "task": "route_to_ring_group", "type": "normal", "valid": true, "tag_ids": [], "message_tts": null, "message_file": null, "workflow_ids": [], "route_to_user_id": null, "call_router_behavior": null, "listen_for_extension": false, "reroute_to_campaign_id": null, "route_to_ring_group_id": 104}]',
          'pool_size': null,
          'pool_options': null,
          'visitor_tracking_mode': null,
          'visitor_tracking_options': null,
          'active': true,
          'tracking_source': null,
          'has_messaging_service': false,
          'dni_script_address': 'https://app.alodev.org/v1/sZwMTAmV/dni.js',
          'incoming_number': '+14154085444',
          'first_incoming_number': {
            'id': 2047,
            'company_id': 7,
            'campaign_id': 11,
            'phone_number': '+14154085444',
            'city': '',
            'state': 'CA',
            'country': 'US',
            'label': 'Federation HQ-incoming number',
            'non_billable': false,
            'is_tollfree': false,
            'is_rented': true,
            'do_not_use': false,
            'is_voice_capable': true,
            'is_fax_capable': true,
            'is_sms_capable': true,
            'is_mms_capable': true,
            'is_fax': false,
            'default_callerid': true,
            'created_at': '2021-06-25 00:03:37',
            'updated_at': '2021-07-08 06:29:07'
          }
        }
      }]
    }
  },
  watch: {
    sequence: function (value) {
      this.$emit('change', value)
    }
  }
}
</script>

<style scoped>

</style>
