name: Quasar Electron Build and Release macOS

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build-capacitor:
    runs-on: ${{ matrix.os-versions }}

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        os-versions: [ macos-latest ]
        node-versions: [ 14.x ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Prepare for app notarization (macOS)
        if: startsWith(matrix.os, 'macos')
        # Import Apple API key for app notarization on macOS
        run: |
          mkdir -p ~/private_keys/
          echo '${{ secrets.api_key }}' > ~/private_keys/AuthKey_${{ secrets.api_key_id }}.p8

      - name: Install dependencies & Quasar
        run: npm install && npm install -g @quasar/cli

      - name: Build/release Electron mac app
        run: npm run build-mac
        env:
          APP_NAME: ${{ secrets.app_name }}
          APP_ENV: ${{ secrets.app_env }}
          APP_DEBUG: ${{ secrets.app_debug }}
          API_URL: ${{ secrets.api_url }}

          # Pusher Configuration
          PUSHER_APP_KEY: ${{ secrets.pusher_app_key }}
          PUSHER_CLUSTER: ${{ secrets.pusher_cluster }}

          # Sentry error logging
          MIX_SENTRY_DSN_PUBLIC: ${{ secrets.mix_sentry_dsn_public }}

          # GIPHY API KEYS
          GIPHY_API_KEY: ${{ secrets.giphy_api_key }}

          # Intercom
          INTERCOM_APP_ID: ${{ secrets.intercom_app_id }}
          INTERCOM_SECRET_KEY: ${{ secrets.intercom_secret_key }}

          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          GITHUB_TOKEN: ${{ secrets.github_token }}

          # macOS code signing certificate
          CSC_LINK: ${{ secrets.mac_certs }}
          CSC_KEY_PASSWORD: ${{ secrets.mac_certs_password }}

          # AnnounceKit
          AK_WIDGET_URL: ${{ secrets.ak_widget_url }}

          # macOS notarization API key
          API_KEY_ID: ${{ secrets.api_key_id }}
          API_KEY_ISSUER_ID: ${{ secrets.api_key_issuer_id }}

      - name: Compressing the build
        run: zip -r ./electron-${{ github.run_number }}.zip ./dist/electron/Packaged/*

      - name: Create a Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: Automated Electron Deployment
          draft: false
          prerelease: false

      - name: Upload a Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./electron-${{ github.run_number }}.zip
          asset_name: electron-${{ github.run_number }}.zip
          asset_content_type: application/zip
