name: Deploy Windows

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      environment:
        description: Dev or Prod
        default: Dev
        required: true

jobs:
  build:
    runs-on: ${{ matrix.os }}

    # Dynamically set the environment name
    environment:
      name: ${{ (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')) && 'Prod' || github.event.inputs.environment }}

    strategy:
      matrix:
        os: [ 'macos-latest' ]
        node-version: [ '18.x' ]
        yarn-version: [ '1.x' ]
    
    steps:
      - name: Set Dynamic Environment
        id: set-env
        run: |
          if [ "${{ github.event_name }}" = "push" ] && [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "DYNAMIC_ENV=Prod" >> $GITHUB_ENV
          else
            echo "DYNAMIC_ENV=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          fi
          echo "Dynamic environment set to ${{ env.DYNAMIC_ENV }}"

      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v7.0.7

      - name: Build details
        run: |
          echo "Environment: ${{ env.DYNAMIC_ENV }}"
          echo "Branch: ${{ steps.branch-name.outputs.current_branch }}"

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Node version
        run: node --version

      - name: Setup Python3
        uses: actions/setup-python@v4
        with:
          python-version: '3.*'
          architecture: 'x64'

      - name: Install dependencies & Quasar
        run: yarn install && yarn global add @quasar/cli

      - name: Make dotenv file
        uses: ozaytsev86/create-env-file@v1
        with:
          ENV_APP_NAME: ${{ secrets.app_name }}
          ENV_APP_ENV: ${{ secrets.app_env }}
          ENV_APP_DEBUG: ${{ secrets.app_debug }}
          ENV_API_URL: ${{ secrets.api_url }}
          ENV_API_REPORTING_URL: ${{ secrets.api_reporting_url }}
          ENV_PUSHER_APP_KEY: ${{ secrets.pusher_app_key }}
          ENV_PUSHER_CLUSTER: ${{ secrets.pusher_cluster }}
          ENV_GIPHY_API_KEY: ${{ secrets.giphy_api_key }}
          ENV_INTERCOM_APP_ID: ${{ secrets.intercom_app_id }}
          ENV_GITHUB_TOKEN: ${{ secrets.github_token }}
          ENV_AK_WIDGET_URL: ${{ secrets.ak_widget_url }}
          ENV_API_KEY_ID: ${{ secrets.api_key_id }}
          ENV_API_KEY_ISSUER_ID: ${{ secrets.api_key_issuer_id }}
          ENV_AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
          ENV_AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
          ENV_AWS_BUCKET: ${{ secrets.aws_bucket }}
          ENV_AWS_BUCKET_REGION: ${{ secrets.aws_bucket_region }}
          ENV_SENTRY_DSN_PUBLIC: ${{ secrets.sentry_dsn_public }}
          ENV_SENTRY_TRACES_SAMPLE_RATE: ${{ secrets.sentry_traces_sample_rate }}
          ENV_SENTRY_AUTH_TOKEN: ${{ secrets.sentry_auth_token }}
          ENV_SENTRY_ORG: ${{ secrets.sentry_org }}
          ENV_SENTRY_PROJECT: ${{ secrets.sentry_project }}
          ENV_RECAPTCHA_SITE_KEY: ${{ secrets.recaptcha_site_key }}
          ENV_DEMO_COMPANY_IDS: ${{ secrets.demo_company_ids }}
          ENV_KYC_SSU_ENABLED: ${{ secrets.kyc_ssu_enabled }}
          ENV_HS_CUSTOM_JS_MOD_GENIUS: ${{ secrets.hs_custom_js_mod_genius }}
          ENV_HS_CUSTOM_JS: ${{ secrets.hs_custom_js }}
          ENV_XMAS_ENABLED: ${{ secrets.xmas_enabled }}
          ENV_XMAS_BANNERS_ENABLED: ${{ secrets.xmas_banners_enabled }}
          ENV_URL_READ_REVIEWS: ${{ secrets.url_read_reviews }}
          ENV_USERPILOT_APPTOKEN: ${{ secrets.userpilot_apptoken }}
          file-name: .env.prod

      - name: Build/release Electron win app
        run: quasar build -d -m electron -T win -b builder -P always
        env:
          APP_NAME: ${{ secrets.app_name }}
          APP_ENV: ${{ secrets.app_env }}
          APP_DEBUG: ${{ secrets.app_debug }}
          API_URL: ${{ secrets.api_url }}
          API_REPORTING_URL: ${{ secrets.api_reporting_url }}

          # Pusher Configuration
          PUSHER_APP_KEY: ${{ secrets.pusher_app_key }}
          PUSHER_CLUSTER: ${{ secrets.pusher_cluster }}

          # GIPHY API KEYS
          GIPHY_API_KEY: ${{ secrets.giphy_api_key }}

          # Intercom
          INTERCOM_APP_ID: ${{ secrets.intercom_app_id }}

          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          GITHUB_TOKEN: ${{ secrets.github_token }}

          # AnnounceKit
          AK_WIDGET_URL: ${{ secrets.ak_widget_url }}

          # macOS notarization API key
          API_KEY_ID: ${{ secrets.api_key_id }}
          API_KEY_ISSUER_ID: ${{ secrets.api_key_issuer_id }}

          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
          AWS_BUCKET: ${{ secrets.aws_bucket }}
          AWS_BUCKET_REGION: ${{ secrets.aws_bucket_region }}

          # Sentry Error Logging
          SENTRY_DSN_PUBLIC: ${{ secrets.sentry_dsn_public }}
          SENTRY_TRACES_SAMPLE_RATE: ${{ secrets.sentry_traces_sample_rate }}

          # Sentry Source Mapping
          SENTRY_AUTH_TOKEN: ${{ secrets.sentry_auth_token }}
          SENTRY_ORG: ${{ secrets.sentry_org }}
          SENTRY_PROJECT: ${{ secrets.sentry_project }}
          #SENTRY_VERSION: ${{ secrets.sentry_version }}

          # Google reCAPTCHA
          RECAPTCHA_SITE_KEY: ${{ secrets.recaptcha_site_key }}

          # Demo Company Ids
          DEMO_COMPANY_IDS: ${{ secrets.demo_company_ids }}

          # SSU/KYC enablement
          KYC_SSU_ENABLED: ${{ secrets.kyc_ssu_enabled }}

          # Moderate Genius
          HS_CUSTOM_JS_MOD_GENIUS: ${{ secrets.hs_custom_js_mod_genius }}
          # All others
          HS_CUSTOM_JS: ${{ secrets.hs_custom_js }}

          # Xmas
          XMAS_ENABLED: ${{ secrets.xmas_enabled }}
          XMAS_BANNERS_ENABLED: ${{ secrets.xmas_banners_enabled }}

          # Reviews
          URL_READ_REVIEWS: ${{ secrets.url_read_reviews }}

          # Userpilot
          USERPILOT_APPTOKEN: ${{ secrets.userpilot_apptoken }}

      - name: Extract Metadata from package.json
        id: pkg
        run: |
          echo "::set-output name=VERSION::$(jq -r '.version' package.json)"
          echo "::set-output name=PRODUCT_NAME::$(jq -r '.productName' package.json)"

      - name: Rename and Move Windows Executable
        run: |
          mv "./dist/electron/Packaged/${{ steps.pkg.outputs.PRODUCT_NAME }} Setup ${{ steps.pkg.outputs.VERSION }}.exe" "./dist/${{ steps.pkg.outputs.PRODUCT_NAME }} Setup Latest.exe"

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/AWSCLIV2.pkg" -o "AWSCLIV2.pkg"
          sudo installer -pkg AWSCLIV2.pkg -target /

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.aws_access_key_id }}
          aws configure set aws_secret_access_key ${{ secrets.aws_secret_access_key }}
          aws configure set default.region ${{ secrets.aws_bucket_region }}

      - name: Upload Renamed File to S3
        run: |
          aws s3 cp "./dist/${{ steps.pkg.outputs.PRODUCT_NAME }} Setup Latest.exe" "s3://${{ secrets.aws_bucket }}/latest/${{ steps.pkg.outputs.PRODUCT_NAME }} Setup Latest.exe" --acl public-read
