name: Deploy macOS

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      environment:
        description: Dev or Prod
        default: Dev
        required: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    environment: ${{ github.event.inputs.environment }}

    strategy:
      matrix:
        os: [ 'macos-latest' ]
        node-version: [ '16.x' ]
        npm-version: [ '9.x' ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.5

      - name: Build details
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Branch: ${{ steps.branch-name.outputs.current_branch }}"

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Update NPM
        run: npm install -g npm@${{ matrix.npm-version }}

      - name: Node version
        run: node --version

      - name: NPM version
        run: npm --version

      - name: Setup Python3
        uses: actions/setup-python@v4
        with:
          python-version: '3.*'
          architecture: 'x64'

      - name: Prepare for app notarization (macOS)
        # Import Apple API key for app notarization on macOS
        run: |
          mkdir -p ~/private_keys/
          echo '${{ secrets.api_key }}' > ~/private_keys/AuthKey_${{ secrets.api_key_id }}.p8

      - name: Install dependencies & Quasar
        run: yarn install && yarn global add @quasar/cli

      - name: Make dotenv file
        uses: ozaytsev86/create-env-file@v1
        with:
          ENV_APP_NAME: ${{ secrets.app_name }}
          ENV_APP_ENV: ${{ secrets.app_env }}
          ENV_APP_DEBUG: ${{ secrets.app_debug }}
          ENV_API_URL: ${{ secrets.api_url }}
          ENV_API_REPORTING_URL: ${{ secrets.api_reporting_url }}
          ENV_PUSHER_APP_KEY: ${{ secrets.pusher_app_key }}
          ENV_PUSHER_CLUSTER: ${{ secrets.pusher_cluster }}
          ENV_MIX_SENTRY_DSN_PUBLIC: ${{ secrets.mix_sentry_dsn_public }}
          ENV_GIPHY_API_KEY: ${{ secrets.giphy_api_key }}
          ENV_INTERCOM_APP_ID: ${{ secrets.intercom_app_id }}
          ENV_INTERCOM_SECRET_KEY: ${{ secrets.intercom_secret_key }}
          ENV_GITHUB_TOKEN: ${{ secrets.github_token }}
          ENV_AK_WIDGET_URL: ${{ secrets.ak_widget_url }}
          ENV_AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
          ENV_AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
          ENV_AWS_BUCKET: ${{ secrets.aws_bucket }}
          ENV_AWS_BUCKET_REGION: ${{ secrets.aws_bucket_region }}
          ENV_RECAPTCHA_SITE_KEY: ${{ secrets.recaptcha_site_key }}
          ENV_DEMO_COMPANY_IDS: ${{ secrets.demo_company_ids }}
          ENV_HS_CUSTOM_JS_MOD_GENIUS: ${{ secrets.hs_custom_js_mod_genius }}
          ENV_HS_CUSTOM_JS: ${{ secrets.hs_custom_js }}
          file-name: .env.prod

      - name: Build/release Electron mac app
        run: quasar build -d -m electron -T mac -b builder -P always
        env:
          APP_NAME: ${{ secrets.app_name }}
          APP_ENV: ${{ secrets.app_env }}
          APP_DEBUG: ${{ secrets.app_debug }}
          API_URL: ${{ secrets.api_url }}
          API_REPORTING_URL: ${{ secrets.api_reporting_url }}

          # Pusher Configuration
          PUSHER_APP_KEY: ${{ secrets.pusher_app_key }}
          PUSHER_CLUSTER: ${{ secrets.pusher_cluster }}

          # GIPHY API KEYS
          GIPHY_API_KEY: ${{ secrets.giphy_api_key }}

          # Intercom
          INTERCOM_APP_ID: ${{ secrets.intercom_app_id }}
          INTERCOM_SECRET_KEY: ${{ secrets.intercom_secret_key }}

          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          GITHUB_TOKEN: ${{ secrets.github_token }}

          # macOS code signing certificate
          CSC_LINK: ${{ secrets.mac_certs }}
          CSC_KEY_PASSWORD: ${{ secrets.mac_certs_password }}

          # AnnounceKit
          AK_WIDGET_URL: ${{ secrets.ak_widget_url }}

          # macOS notarization API key
          API_KEY_ID: ${{ secrets.api_key_id }}
          API_KEY_ISSUER_ID: ${{ secrets.api_key_issuer_id }}

          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
          AWS_BUCKET: ${{ secrets.aws_bucket }}
          AWS_BUCKET_REGION: ${{ secrets.aws_bucket_region }}

          # Sentry Error Logging
          SENTRY_DSN_PUBLIC: ${{ secrets.sentry_dsn_public }}
          SENTRY_TRACES_SAMPLE_RATE: ${{ secrets.sentry_traces_sample_rate }}

          # Sentry Source Mapping
          SENTRY_AUTH_TOKEN: ${{ secrets.sentry_auth_token }}
          SENTRY_ORG: ${{ secrets.sentry_org }}
          SENTRY_PROJECT: ${{ secrets.sentry_project }}
          #SENTRY_VERSION: ${{ secrets.sentry_version }}

          # Google reCAPTCHA
          RECAPTCHA_SITE_KEY: ${{ secrets.recaptcha_site_key }}

          # Demo Company Ids
          DEMO_COMPANY_IDS: ${{ secrets.demo_company_ids }}

          # Moderate Genius
          HS_CUSTOM_JS_MOD_GENIUS: ${{ secrets.hs_custom_js_mod_genius }}
          # All others
          HS_CUSTOM_JS: ${{ secrets.hs_custom_js }}
