name: Environment Destruction

on:
  push:
    branches:
      - 'feature/PLAT-1002/add-pipeline-v2'
  pull_request:
    branches:
      - develop
    types: [closed, open]

jobs:
  trigger:
    if: github.event.pull_request.merged == true
    name: jenkins
    runs-on: ubuntu-latest
    steps:
      - name: trigger destruction workflow
        run: |
          apt-get update && apg-get install -y curl
          curl -X POST "https://jenkins.alodev.org/job/DevOps/job/talk2_destruction_workflow/buildWithParameters?PR_NUMBER=${{ github.event.number }}" --user ${{ secrets.jenkins_user }}:${{ secrets.jenkins_token }}
